
website:
  title: "CATe Pathway Evaluation"
  navbar:
    left:
      - href: index.qmd
        text: Summary
  comments: 
    giscus: 
      repo: kurtis14/CATe_pathway_evaluation
        
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: source

tbl-cap-location: top
fig-cap-location: top